# Generated by Django 4.1 on 2023-12-30 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sampleApp', '0008_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reactionCounter',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
