# Generated by Django 4.1 on 2024-01-03 17:58

from django.db import migrations, models
import sampleApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0014_alter_postattachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='attachment',
            field=models.FileField(upload_to=sampleApp.models.get_directory_path),
        ),
    ]
