# Generated by Django 4.1 on 2024-01-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0015_alter_postattachment_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Something',
        ),
    ]
